#!/bin/bash
#   ————————————————————————————————————————————————————
#   Main bootstrap file
#
#   @author       dale@snowdon.dev
#   ————————————————————————————————————————————————————

. -- ~/Repositories/bash-profile/variables

. -- "$BP_CODE_SOURCE/env"

## for each file load the source
for f in $BP_CODE_SOURCE/src/*; do
	if [[ "$f" = * ]]; then
		. $f
	fi
done
