#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# load variables into shell
. -- "$DIR/variables"

# create sym links for profile
if [ "$SHELL" == "/bin/zsh" ]; then
  # link profile
  ln -sf "$BP_CODE_SOURCE/profile" "$BP_BASH_SOURCE/.zprofile"

  # source rc given its not already
  if ! grep -Fxq "source $BP_CODE_SOURCE/bootstrap" ~/.zshrc; then
    echo "source $BP_CODE_SOURCE/bootstrap" >> ~/.zshrc
  fi
else 
  ln -sf "$BP_CODE_SOURCE/profile" "$BP_BASH_SOURCE/.bash_profile"
  ln -sf "$BP_CODE_SOURCE/bootstrap" "$BP_BASH_SOURCE/.bashrc"
fi

if hash nvim 2> /dev/null; then
  NVIM_PATH="$BP_BASH_SOURCE/.config/nvim/init.vim"
  command mkdir "$BP_BASH_SOURCE/.config/nvim/" 2> /dev/null
  ln -sf "$BP_CODE_SOURCE/.vimrc" "$NVIM_PATH"
else
  ln -sf "$BP_CODE_SOURCE/.vimrc" "$BP_BASH_SOURCE/.vimrc"
fi

# setup bin permissions
chmod -R 775 "$DIR/bin"

if hash brew 2> /dev/null; then
  # install all programs from brew given they don't already exist
  if [ ! "`type trash`" = "trash is /usr/local/bin/trash" ]; then
    brew install trash
  fi

  if [ ! "`type rename`" = "rename is /usr/local/bin/rename" ]; then
    brew install rename
  fi

  if [ ! "`type bat`" = "bat is /usr/local/bin/bat" ]; then
    brew install bat
  fi

  if [ ! "`type tree`" = "tree is /usr/local/bin/tree" ]; then
    brew install tree
  fi

  if [ ! "`type htop`" = "htop is /usr/local/bin/htop" ]; then
    brew install htop 
  fi

  if [ ! "`type go`" = "go is /usr/local/bin/go" ]; then
    brew install go
  fi

  if [ ! "`type php`" = "php is /usr/local/bin/php" ]; then
    brew install php@7.4
  fi

  # @todo nvim dependencies
else
  # we must be linux use apt-get 
  if [ ! "`type tree`" = "tree is /usr/bin/tree" ]; then
    sudo apt-get install tree -y
  fi

  if [ ! "`type rename`" = "rename is /usr/bin/rename" ]; then
    sudo apt-get install rename -y
  fi
fi



# clean up
unset DIR
